server:
  port: 8080

spring:
  application:
    name: application
  profiles:
    active: dev, awsdb, awsS3, jwt, mail
  config:
    import: optional:configserver:http://43.201.86.153:9999 # config server 주소

# Spring Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh